// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYl9hg0lzvuEaWCmjEZiKwPssnEXbvPzU',
    appId: '1:321039910286:web:aa45672bd128faf2ba50df',
    messagingSenderId: '321039910286',
    projectId: 'cloud-messaging-app-bd6a8',
    authDomain: 'cloud-messaging-app-bd6a8.firebaseapp.com',
    storageBucket: 'cloud-messaging-app-bd6a8.firebasestorage.app',
    measurementId: 'G-LBNVBGYG94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK9exUu5SJTWbhQDmxApMqOm2NxDFv7Dc',
    appId: '1:321039910286:android:e1b0df93f13741d1ba50df',
    messagingSenderId: '321039910286',
    projectId: 'cloud-messaging-app-bd6a8',
    storageBucket: 'cloud-messaging-app-bd6a8.firebasestorage.app',
  );
}
